Algoritmo "conversão_dolar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2022
Var
// Seção de Declarações das variáveis 
// considerar dolar = 5,13
reais, dolares: Real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Quantos reais eu tenho?")
Leia(reais)
dolares <- reais/5.13
Escreva("Eu posso ter ", dolares, " dolares")

Fimalgoritmo